config/routes.rb
Rails.application.routes.draw do
  resources :car_makes
  resources :categories
  resources :leads, only: [:create]
  resources :riders, only: [:create, :destroy]
  resources :messages, only: [:create, :index] do 
    collection { post :import_users }
  end

  resources :events
  resources :reports
  resources :trips
  resources :plans
  resources :vehicles

  get '/messages/trip/:trip_id',  to: 'messages#for_single_trip'
  get '/users/profile',           to: 'profiles#index',           as: :profile
  get '/users/settings',          to: 'profiles#settings',        as: :settings
  get '/leads/trip/:trip_id',     to: 'leads#for_single_trip',    as: :leads_for_trip
  get '/trips/search/any-trip',   to: 'trips#search',             as: :trips_search
  get '/home/load_more',          to: 'pages#home'
  get '/messages/users.csv',      to: 'messages#export_users_csv', as: :export_users_csv

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
    # sessions: 'users/sessions',
    # passwords: 'users/passwords',
    # registrations: 'users/registrations',
    # confirmations: 'users/confirmations'
  }

  root to: 'pages#home'

  # namespace :api, defaults: { format: :json } do
  #   namespace :v1 do
  #     mount_devise_token_auth_for "User", at: "auth",
  #       controllers: {
  #         sessions: 'api/v1/devise_token_auth/sessions'
  #       }
  #     resources :appointments, only: [ :index, :show, :create, :update, :destroy ]
  #   end
  # end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_authenticate_modal.html.erb
<div class="modal fade" id="modalAuthenticateForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
  aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header text-center">
        <h4 class="modal-title w-100 font-weight-bold">Write to us</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body mx-3">
        <div class="md-form mb-5">
          <i class="fas fa-user prefix grey-text"></i>
          <input type="text" id="form34" class="form-control validate">
          <label data-error="wrong" data-success="right" for="form34">Your name</label>
        </div>

        <div class="md-form mb-5">
          <i class="fas fa-envelope prefix grey-text"></i>
          <input type="email" id="form29" class="form-control validate">
          <label data-error="wrong" data-success="right" for="form29">Your email</label>
        </div>

        <div class="md-form mb-5">
          <i class="fas fa-tag prefix grey-text"></i>
          <input type="text" id="form32" class="form-control validate">
          <label data-error="wrong" data-success="right" for="form32">Subject</label>
        </div>

        <div class="md-form">
          <i class="fas fa-pencil prefix grey-text"></i>
          <textarea type="text" id="form8" class="md-textarea form-control" rows="4"></textarea>
          <label data-error="wrong" data-success="right" for="form8">Your message</label>
        </div>

      </div>
      <div class="modal-footer d-flex justify-content-center">
        <button class="btn btn-unique">Send <i class="fas fa-paper-plane-o ml-1"></i></button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_banner.html.erb
<%
=begin%>
 <div class="container-search">
  <div class="top-search">
    <div class="input-container-search">
      <input type="text" id="search-box" class="search-input" placeholder="Find work lift clubs, social events and long distance home rides"/>
      <div id="stats"></div>
    </div>
     <div class="search-button">
      <i class="fa fa-search"></i>
    </div>
</div> 
<%
=end%>
 <%
=begin%>
 <h2 class="mb-3 intro">Find or offer rides to the workplace, social event or cross province suburb you are travelling to.</h2> 

 <section id="sunfish">
  <div class="banner"> 


 <div>
      <figure>
        <img src="https://scontent.fjnb8-1.fna.fbcdn.net/v/t1.0-9/60796127_840712849597000_7543304053271298048_o.jpg?_nc_cat=110&_nc_oc=AQkfDLbdt0UyXp7FPFtccJw7xiO-4-4GCbkpwB815DOvKe_7_sRZsAFlWvBPzEyhGhw&_nc_ht=scontent.fjnb8-1.fna&oh=ed494b748a0cf5da5d2ea6f6d2f9ee84&oe=5E4BFBC1" alt="earlybirds.co.za banner"> 
<%
=end%>
        <%
=begin%>
 <figcaption class="top"><h3>Explore lift clubs to your workplace, social events and cross province home</h3></figcaption> 
<%
=end%>
        <%
=begin%>
 <figcaption class="button"> 
<%= button_to 'Offer a ride', trips_path, :class=>"btn btn-bnb", :method => :get %> 

 <%= button_to 'Find a ride', trips_path, :class=>"btn btn-bnb", :method => :get %> 

 </figcaption>
        <figcaption class="sign">
          <div class="_exn6n2"><svg viewBox="0 0 470 239" fill="#616668" height="50px" aria-label="" width="98.32635983263597px"></svg></div>
        </figcaption>
      </figure>
    </div>
  </div>
</section>  
<%
=end%>

 <%
=begin%>
 <p class="banner-text">
    Find or offer rides to the workplace, social event or cross province suburb you are already travelling to.
  </p> 
<%
=end%>

<div class="jumbotron">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <p class="banner-text">
                    Find or offer rides to the cross province city/town you are already travelling to.
                </p>
                <a href="/trips/new" class="btn btn-banner">Offering a ride?</a> <a href="#trips" class="btn btn-banner">Looking for a ride?</a>

            </div>
        </div>
    </div>
</div>

app/views/shared/_daily_cards.html.erb
<h2 id="trips"><%= header %><%= search_results_count trips %></h2>
<div class="row top-buffer paginated-cards mt-4">
  <% trips.each do |trip| %>
    <div class="col-md-4 col-sm-12 box-placeholder box-placeholder-daily">
      <div class="p-4">
        <span class="category text link"></span>
        <h4 class="text line"></h4>
        <h4 class="text"></h4>
      </div>
      <hr>
      <div class="image">
        <div class="embed-responsive embed-responsive-16by9"></div>
      </div>
      <hr>
      <div class="excerpt p-4">
        <div class="text line"></div>
        <div class="text line"></div>
        <div class="text"></div>
      </div>
    </div>

    <div class="col-md-4 col-sm-12 daily-trip" style="margin-bottom: 20px">
      <div class="card card__dark card__dark--magenta custom">
        <div class="media media--16-9" style="background-image: url(<%= url_for(trip.vehicle.image) %>); background-repeat: no-repeat; background-size: cover;"></div>
            <div class="primary-title">
              <div class="primary-text float-right price btn btn-info">
                  R<%= trip.price %>
              </div>
              <div class="primary-text">
                <p class="text-center" style="padding-bottom:10px"><%= truncate(trip.short_start_location, length: 30) %></p>
                  <div class="from_to">
                    <span>TO</span> 
                  </div>
                <p class="text-center"><%= truncate(trip.short_end_location, length: 30) %></p> 
              </div>
            </div>
            <div class="d-inline p-2 text-center" style="margin-top:10px;">Departs at <%= trip_time(trip.kind, trip.departure_times) %></div>
            <div class="d-inline p-2 bg-secondary text-white text-center">
                <div class="action-icons icon-color--yellow"><span><i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star"></i>
             </div>
              Super driver
             </div>
            <div class="actions border-top">
              <div class="action-buttons float-right action-buttons-daily-cards">
                <%= button_to "View Details", trip_path(trip), :method => :get, :class => "button", :type => "button" %>
              </div>
              <div class="action-icons float-left">
                <div class="social-icons">
                  <%= social_share(trip) %>
                </div>
              </div>
          </div>
        </div> 
    </div> 
  <% end %>
  <%
=begin%>
 <% if trips.count > WillPaginate.per_page %>
    <div class="apple_pagination">
      <div class="page_info">
      <%= page_entries_info trips  %>
      </div>
      <%= will_paginate trips, :container => false %>
    </div>
  <% end %> 
<%
=end%>
</div>
<%
=begin%>
 <h3 class="view-more"><%= "Show all #{trips.size} + lift clubs <i class='fa fa-angle-right'></i>".html_safe if (trips.size - 9) > 0 %></h3>   
<%
=end%>

app/views/shared/_events_advert.html.erb
 <section class="Section-sc-1y89xsy-0 brronC">
    <div direction="row" class="Row-kr12on-0 jxnwlb">
    <div class="col-md-12 col-sm-12">
        <h2 class="styled__Title-sc-17byy7f-2 kFLZkN">Browse our available social events destinations</h2>
    </div>
    <div direction="row" class="Row-kr12on-0 iIoJkK">
        <% Category.all.each do |category| %>
            <div class="col-md-2 col-sm-12">
                <%= link_to category.name, category_path(category), :class=>"styled__TileText-sc-17byy7f-1 ezTZVn" %>
            </div>
        <% end %>
    </div>
</section> 

app/views/shared/_events_slider.html.erb
    <h2>Social events rides</h2>
        <div data-slick='{"slidesToShow": 3, "slidesToScroll": 3}' class="scroller responsive data left-align-slick">
            <% @social_trips.each do |trip| %>
                    <!-- Card example 06 -->
                    <div class="card card__small card__dark card__dark--magenta">
                        <div class="media" style="background-image: url(https://earlybirds.co.za<%= Rails.application.routes.url_helpers.rails_representation_url(trip.vehicle.image.variant(resize: "500x500").processed, only_path: true) %>); background-repeat: no-repeat; background-size: cover;"></div>
                        <div class="primary-title">
                            <div class="primary-text"><%= link_to trip.event.name, event_path(trip.event), :class => "event-link" %></div>
                            <div class="secondary-text">from <%= trip.start_location %></div>
                            <p><%= trip_time(trip.kind, trip.departure_times) %></p>
                        </div>
                        <div class="actions border-top">
                            <div class="action-buttons">
                                <%= button_to "View Details", trip_path(trip), :method => :get, :class => "button", :type => "button" %>
                            </div>
                        </div>
                    </div>
            <% end %>
    </div>

app/views/shared/_flashes.html.erb
<br />
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<%= render 'shared/authenticate_modal' %>
<section class="space"></section>
<footer class="footer">
    <section class="footer-top">
      <section class="links-section">
        <div id="company-links" class="links-list">
          <h5 class="links-header">Company</h5>
          <a class="link-item" href="#">About</a>
          <a class="link-item" href="#">Careers</a>
          <a class="link-item" href="#">Press</a>
          <a class="link-item" href="#">Blog</a>
          <a class="link-item" href="#">Help</a>
          <a class="link-item" href="#">Policies</a>
          <a class="link-item" href="#">Crime Reponse</a>
          <a class="link-item" href="#">Terms & Privacy</a>
        </div>
        <div id="discover-links" class="links-list">
          <h5 class="links-header">Discover</h5>
          <a class="link-item" href="#">Trust & Safety</a>
          <a class="link-item" href="#">Earlybirds Picks</a>
          <%
=begin%>
 <a class="link-item" href="#">Work Rides</a> 
<%
=end%>
          <%
=begin%>
 <a class="link-item" href="#">Social Events Rides</a> 
<%
=end%>
          <a class="link-item" href="#">Cross Province Rides</a>
          <a class="link-item" href="#">Site Map</a>
        </div>
        <div id="hosting-links" class="links-list">
          <h5 class="links-header">Driving</h5>
          <a class="link-item" href="#">Why Share Ride</a>
          <a class="link-item" href="#">Responsible Ride Sharing</a>
          <a class="link-item" href="#">Ride Sharing Safety</a>
          <a class="link-item" href="#">Instant Bookings</a>
          <a class="link-item" href="/trips/new">Create a ride</a>
        </div>
        <%
=begin%>
 <div id="hosting-links" class="links-list">
          <h5 class="links-header">Browse rides by events</h5>
          <% Event.limit(5).each do |event| %>
            <%= link_to truncate(event.name, length: 48), event_path(event.slug), :class=>"link-item" %>
          <% end %>
        </div> 
<%
=end%>
      </section>
      <section class="dropdown-section">
        
      </section>
    </section>
    <div id="mobile-links" class="links-list-mobile">
      <a class="link-item" href="/trips/new">Create a ride</a>
      <a class="link-item" href="#">About</a>
      <a class="link-item" href="#">Careers</a>
      <a class="link-item" href="#">Press</a>
      <a class="link-item" href="#">Blog</a>
      <a class="link-item" href="#">Terms & Policy</a>
    </div>
    <section class="footer-bottom">
      <div class="footer-bar"></div>
      <h4 class="join">Join Us On</h4>
      <section class="socialIcons-section">
        <div class="circle"><a href="https://www.facebook.com/earlybirds.co.za/" target='blank' class="icon"><i class="fa fa-facebook" aria-hidden="true"></i></a></div>
        <div class="circle"><a href="https://twitter.com/earlybirdscoza" target='blank' class="icon icon-twitter-footer"><i class="fa fa-twitter" aria-hidden="true"></i></a></div>
        <%
=begin%>
 <div class="circle"><a href="#" class="icon"><i class="fa fa-linkedin" aria-hidden="true"></i></a></div> 
<%
=end%>
        <%
=begin%>
 <div class="circle"><a href="#" class="icon"><i class="fa fa-youtube-play" aria-hidden="true"></i></a></div> 
<%
=end%>
        <div class="circle"><a href="https://www.instagram.com/earlybirds.co.za/" target='blank' class="icon"><i class="fa fa-instagram" aria-hidden="true"></i></a></div>
      </section>
      <p class="copywright">&#xa9 Lifiti, Inc.</p>
    </section>
</footer>

app/views/shared/_long_slider.html.erb
<h2>Long distance rides</h2>
<div data-slick='{"slidesToShow": 3, "slidesToScroll": 3}' class="scroller responsive data left-align-slick">
    <% @cross_province_trips.each do |trip| %>
        <%
=begin%>
 <div class="box-placeholder box-placeholder-long">
            <div class="p-5">
                <span class="category text link"></span>
                <h4 class="text line"></h4>
                <h4 class="text"></h4>
            </div>
            <hr>
            <div class="excerpt p-4">
                <div class="text line"></div>
                <div class="text line"></div>
                <div class="text"></div>
            </div>
            <hr>
        </div> 
<%
=end%>
        <!-- Card example 06 -->
        <div class="card card__dark card__dark--magenta long-trip">
            <div class="media media--16-9" style="background-image: url(https://earlybirds.co.za<%= Rails.application.routes.url_helpers.rails_representation_url(trip.vehicle.image.variant(resize: "500x500").processed, only_path: true) %>); background-repeat: no-repeat; background-size: cover;"></div>
            <div class="primary-title">
                <div class="primary-text float-rightprice btn btn-info price">
                    R<%= trip.price %>
                </div>
                <div class="primary-text">
                 <p class="text-center" style="padding-bottom:10px"><%= truncate(trip.short_start_location, length: 30) %></p>
                 <div class="from_to">
                    <span>TO</span> 
                  </div>
                  <p class="text-center" style="padding-bottom:10px"><%= truncate(trip.short_end_location, length: 30) %></p>
                </div>
                </div>
                <div class="text-center" style="margin-top:15px;"><i class="fa fa-clock-o"></i><%= trip_time(trip.kind, trip.departure_times) %></div>
                <div class="bg-secondary text-white text-center" style="padding:6px; margin-top:5px">
                    <div class="action-icons icon-color--yellow"><span><i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star"></i>
                    </div>
                    Super driver
                </div>
  
                <div class="actions border-top">
                    <div class="action-buttons float-right action-buttons-daily-cards">
                        <%= button_to "View Details", trip_path(trip), :method => :get, :class => "button", :type => "button" %>
                    </div>
                    <div class="action-icons">
                        <div class="social-icons">
                            <%= social_share(trip) %>
                        </div>
                    </div>
                </div>
        </div> 
    <% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png", height: 50 %>
  <% end %>
  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%
=begin%>
 <%= link_to "Create a ride", "#", class: "navbar-wagon-item navbar-wagon-link" %> 
<%
=end%>
      <%= link_to "Create a ride", new_trip_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Your rides", profile_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Your messages", messages_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Your vehicles", vehicles_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag set_user_profile_image(current_user), class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to profile_path do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to settings_path do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Account details") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <%= link_to "Create a ride", new_trip_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, {:class => "navbar-wagon-item navbar-wagon-link"} %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <% if user_signed_in? %>
          <li><%= link_to "Create a ride", new_trip_path %></li>
          <li><%= link_to "Your rides", profile_path %></li>
          <li><%= link_to "Your messages", messages_path %></li>
          <li><%= link_to "Your vehicles", vehicles_path %></li>
          <li>
            <%= link_to profile_path do %>
              <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
            <% end %>
          </li>
          <li>
            <%= link_to settings_path do %>
              <i class="fa fa-cog"></i>  <%= t(".settings", default: "Account details") %>
            <% end %>
          </li>
        <% else %>
          <li><%= link_to "Create a ride", new_trip_path %></li>

          <!-- Login link (when logged out) -->
          <li><%= link_to t(".sign_in", default: "Login"), new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_rider_adverts.html.erb
<section class="Section-sc-1y89xsy-0 brronC">
<h2>Why use earlybirds for your long distance rides</h2>
<div class="features-block container">
    <div class="row spacing-lg-20 mt-md-112">
        <div class="col-sm-12 col-md-4 mt-56 mt-md-0">
            <%= image_tag "icon3.svg", height: 70, width: 70, alt: "car image", class: "feature-img feature-img-car float-left float-md-none mr-24" %>
            <div class="feature-content ml-104 mr-md-24 ml-md-0">
                <h3>Convenient pickups/drop offs</h3>
                <p class="mt-8 mt-md-16 mb-0 color-grey">Get picked up at your departing suburb and get dropped at your destination suburb.</p>
            </div>
        </div>
        <div class="col s12 m4 mt-44 mt-md-0">
        <%= image_tag "icon1.svg", height: 70, width: 70, alt: "car image", class: "feature-img feature-img-car float-left float-md-none mr-24" %>
        <div class="feature-content ml-104 mr-md-24 ml-md-0">
                <h3>Normal prices</h3>
                <p class="mt-8 mt-md-16 mb-0 color-grey">You pay prices that are close to normal taxi fares, using your convenient payment method! </p>
            </div>
        </div>
        <div class="col-sm-12 col-md-4 mt-44 mt-md-0">
        <%= image_tag "icon2.svg", height: 70, width: 70, alt: "car image", class: "feature-img feature-img-car float-left float-md-none mr-24" %>
        <div class="feature-content ml-104 mr-md-24 ml-md-0">
                <h3>Easy to use</h3><p class="mt-8 mt-md-16 mb-0 color-grey">Multiple communication channels with your driver. Convenient payment models. Safety assured.</p>
            </div>
        </div>
    </div>
</div>
</section>