config/routes.rb
Rails.application.routes.draw do
  resources :car_makes
  resources :categories
  resources :leads, only: [:create]
  resources :riders, only: [:create, :destroy]
  resources :messages, only: [:create, :index] do 
    collection { post :import_users }
  end

  resources :events
  resources :reports
  resources :trips
  resources :plans
  resources :vehicles

  get '/messages/trip/:trip_id',  to: 'messages#for_single_trip'
  get '/users/profile',           to: 'profiles#index',           as: :profile
  get '/users/settings',          to: 'profiles#settings',        as: :settings
  get '/leads/trip/:trip_id',     to: 'leads#for_single_trip',    as: :leads_for_trip
  get '/trips/search/any-trip',   to: 'trips#search',             as: :trips_search
  get '/home/load_more',          to: 'pages#home'
  get '/messages/users.csv',      to: 'messages#export_users_csv', as: :export_users_csv

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
    # sessions: 'users/sessions',
    # passwords: 'users/passwords',
    # registrations: 'users/registrations',
    # confirmations: 'users/confirmations'
  }

  root to: 'pages#home'

  # namespace :api, defaults: { format: :json } do
  #   namespace :v1 do
  #     mount_devise_token_auth_for "User", at: "auth",
  #       controllers: {
  #         sessions: 'api/v1/devise_token_auth/sessions'
  #       }
  #     resources :appointments, only: [ :index, :show, :create, :update, :destroy ]
  #   end
  # end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  include Resizable
  belongs_to :user
  has_many :trips, dependent: :destroy
  has_one_attached :image

  validates :make, :licence_plate, :model, presence: true
  validate :vehicle_image?


  def vehicle_image?
    errors.add(:base, 'Please upload a picture of your vehicle.') unless image.attached?
  end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  include TinifyImage

  before_action :set_vehicle, only: [:show, :edit, :update, :destroy]
  after_action  :attach_image, only: [:create, :update]
  # after_action  :update_role, only: [:create, :update]
  # before_action :require_vehicle_images, only: %i[update create]

  # GET /vehicles
  # GET /vehicles.json
  def index
    @vehicles = policy_scope(Vehicle).where(user: current_user)
  end

  # GET /vehicles/1
  # GET /vehicles/1.json
  def show
    authorize @vehicle
  end

  # GET /vehicles/new
  def new
    @vehicle = Vehicle.new
    authorize @vehicle
  end

  # GET /vehicles/1/edit
  def edit
    authorize @vehicle
  end

  # POST /vehicles
  # POST /vehicles.json
  def create
    @vehicle      = Vehicle.new(vehicle_params)
    @vehicle.user = current_user
    authorize @vehicle
      
    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to new_trip_path, notice: 'Vehicle was successfully created. You can now create your ride' }
        format.json { render :show, status: :created, location: @vehicle }
      else
        format.html { render :new }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicles/1
  # PATCH/PUT /vehicles/1.json
  def update
    authorize @vehicle
    respond_to do |format|
      if @vehicle.update(vehicle_params)
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully updated.' }
        format.json { render :show, status: :ok, location: @vehicle }
      else
        format.html { render :edit }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicles/1
  # DELETE /vehicles/1.json
  def destroy
    @vehicle.destroy
    respond_to do |format|
      format.html { redirect_to vehicles_url, notice: 'Vehicle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle
      @vehicle = policy_scope(Vehicle).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vehicle_params
      params.require(:vehicle).permit(:make, :model, :user_id, :licence_plate, :color, :is_verified, :image)
    end

    def attach_image
      return unless params[:vehicle][:image].present?
      image = open(tinify(params[:vehicle][:image].tempfile))
      @vehicle.image.attach(io: image, filename: "#{@vehicle.make}-#{@vehicle.id}.png")
    end

    def update_role
      current_user.update!(role: "driver", cellphone: '0000000000') unless current_user.driver?
    end
end

app/views/vehicles/_form.html.erb
<%= simple_form_for(@vehicle) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%
=begin%>
 <%= f.select(:make, CarsService.makes, {}, {:class => "selectpicker makes", :id => "makes", 'data-live-search' => "true"}) %> 
<%
=end%>
    <%= f.input :make, :collection => CarMake.all, :value_method => :name %> 
    <%= f.input :model, :collection => [] %>
    <%= f.input :licence_plate, :placeholder => 'Do not leave any spaces.', :hint => 'We do not share this, it is used to verify you are the owner' %>
    <%= f.input :color %>
    <%
=begin%>
 <%= f.input :is_verified %> 
<%
=end%>
    <%= f.file_field :image, direct_upload: true, :hint => 'Avoid showing the plate number.' %>

  <div class="form-actions">
    <%= f.button :submit, :class=>"btn-primary" %>
  </div>
<% end %>

app/views/vehicles/edit.html.erb
<h1>Editing Vehicle</h1>

<%= render 'form', vehicle: @vehicle %>

<%= link_to 'Show', @vehicle %> |
<%= link_to 'Back', vehicles_path %>

app/views/vehicles/index.html.erb
<%
=begin%>
 <p id="notice"><%= notice %></p>

<h1>Vehicles</h1>

<table>
  <thead>
    <tr>
      <th>Make</th>
      <th>Model</th>
      <th>User</th>
      <th>Licence plate</th>
      <th>Color</th>
      <th>Is verified</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vehicles.each do |vehicle| %>
      <tr>
        <td><%= vehicle.make %></td>
        <td><%= vehicle.model %></td>
        <td><%= vehicle.user %></td>
        <td><%= vehicle.licence_plate %></td>
        <td><%= vehicle.color %></td>
        <td><%= vehicle.is_verified %></td>
        
      </tr>
    <% end %>
  </tbody>
</table> 
<%
=end%>

<br>

<%= link_to 'New Vehicle', new_vehicle_path %>
<h2>Your vehicles</h2>
<div class="row">
  <% @vehicles.each do |vehicle| %>
    <div class="col-md-3 col-sm-12">
      <!-- Card example 06 -->
      <div class="card card__dark card__dark--magenta custom">
        <div class="media media--16-9"> <img src="<%= url_for(vehicle.image) %>" alt="" width="640" height="426" class="lazy"> </div>
            <div class="primary-title">
              <div class="primary-text float-right price">
                  <%= vehicle.color %>
              </div>
              <div class="primary-text">
                  <%= link_to "#{vehicle.make} - #{vehicle.model}", vehicle_path(vehicle) %>
              </div>
              <div class="secondary-text">
                Verified: <%= vehicle.is_verified? %>
              </div>
               <div class="action-icons float-left">
                <div class="social-icons">
                  <%= link_to 'Show', vehicle %>
                  <%= link_to 'Destroy', vehicle, method: :delete, data: { confirm: 'Are you sure?' } %>
                </div>
              </div>
            </div>
            <div class="actions border-top">
              <div class="action-buttons float-left action-buttons-daily-cards">
                <%= button_to 'Edit vehicle', edit_vehicle_path(vehicle), method: :get, :class => "button", :type => "button" %>
              </div>
          </div>
        </div> 
    </div> 
  <% end %>
</div>

app/views/vehicles/new.html.erb
<h2>New Vehicle</h2>

<%= render 'form', vehicle: @vehicle %>

<%= link_to 'Back', vehicles_path %>

app/views/vehicles/show.html.erb
<%
=begin%>
 <p id="notice"><%= notice %></p>

<p>
  <strong>Make:</strong>
  <%= @vehicle.make %>
</p>

<p>
  <strong>Model:</strong>
  <%= @vehicle.model %>
</p>

<p>
  <strong>User:</strong>
  <%= @vehicle.user %>
</p>

<p>
  <strong>Licence plate:</strong>
  <%= @vehicle.licence_plate %>
</p>

<p>
  <strong>Color:</strong>
  <%= @vehicle.color %>
</p>

<p>
  <strong>Is verified:</strong>
  <%= @vehicle.is_verified %>
</p>

<p>
  <%= image_tag url_for(@vehicle.image) %>
</p>

<%= link_to 'Edit', edit_vehicle_path(@vehicle) %> |
<%= link_to 'Back', vehicles_path %> 
<%
=end%>
<%= link_to 'Create new trip', new_trip_path %>
<section class="better-space"></section>
<div class="driver-details">
    <h3><%= "#{@vehicle.make} - #{@vehicle.model}" %> by <%= link_to @vehicle.user.full_name, profile_path %> </i></h3>
    <div class="details">
        <div class="driver-photo">
          <%= image_tag @vehicle.thumbnail %>
        </div>
        <div class="detail">
            <span>Licence plate: <span><%= @vehicle.licence_plate %></span> </span>
            <span>Color: <span> <%= @vehicle.color %></span> </span>
            <span>Verified: <span><%= @vehicle.is_verified %></span> </span>
            <%= link_to 'Edit', edit_vehicle_path(@vehicle) %> |<%= link_to 'Back', vehicles_path %> 
        </div>
    </div>
</div>