config/routes.rb
Rails.application.routes.draw do
  resources :car_makes
  resources :categories
  resources :leads, only: [:create]
  resources :riders, only: [:create, :destroy]
  resources :messages, only: [:create, :index] do 
    collection { post :import_users }
  end

  resources :events
  resources :reports
  resources :trips
  resources :plans
  resources :vehicles

  get '/messages/trip/:trip_id',  to: 'messages#for_single_trip'
  get '/users/profile',           to: 'profiles#index',           as: :profile
  get '/users/settings',          to: 'profiles#settings',        as: :settings
  get '/leads/trip/:trip_id',     to: 'leads#for_single_trip',    as: :leads_for_trip
  get '/trips/search/any-trip',   to: 'trips#search',             as: :trips_search
  get '/home/load_more',          to: 'pages#home'
  get '/messages/users.csv',      to: 'messages#export_users_csv', as: :export_users_csv

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
    # sessions: 'users/sessions',
    # passwords: 'users/passwords',
    # registrations: 'users/registrations',
    # confirmations: 'users/confirmations'
  }

  root to: 'pages#home'

  # namespace :api, defaults: { format: :json } do
  #   namespace :v1 do
  #     mount_devise_token_auth_for "User", at: "auth",
  #       controllers: {
  #         sessions: 'api/v1/devise_token_auth/sessions'
  #       }
  #     resources :appointments, only: [ :index, :show, :create, :update, :destroy ]
  #   end
  # end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
    include Resizable
    include AlgoliaSearch

    algoliasearch do
      attributes :name, :description, :slug
      searchableAttributes ['name', 'unordered(description)']

    end

    extend FriendlyId
    friendly_id :slugger, use: :slugged

    validates :name, :description, presence: true
    validates_uniqueness_of :name
    validates :name, length: {minimum: 3, maximum: 30}
    validates :description, length: {minimum: 3, maximum: 500}
    has_many :events
    validate :category_image?

    has_one_attached :image

    def slugger
        name
    end
    
    def should_generate_new_friendly_id?
        name_changed?
    end


    def category_image?
        errors.add(:base, 'Please upload a cover image for your category.') unless image.attached?
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, except: [:new, :create, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = policy_scope(Category).all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    authorize @category
  end

  # GET /categories/new
  def new
    @category = Category.new
    authorize @category
  end

  # GET /categories/1/edit
  def edit
    authorize @category
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)
    authorize @category

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    authorize @category
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    authorize @category
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = policy_scope(Category.friendly).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :description, :image)
    end
end

app/helpers/category_helper.rb
module CategoryHelper
    def trips_for_category category_id
        events = Event.where(category_id: category_id).pluck(:id)
        Trip.where(event_id: events)
    end

    def trips_for_other_events category_id
        (Trip.events_trips - trips_for_category(category_id))
    end
end

app/views/categories/_form.html.erb
<%= simple_form_for(@category) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :image, :hint=>'Cover image for category' %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, :class=>"btn-primary" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<%
=begin%>
 <p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.description %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %> 
<%
=end%>
<%
=begin%>
 <p id="notice"><%= notice %></p>

<h1>Events</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Start time</th>
      <th>End time</th>
      <th>Ticket link</th>
      <th>Expired</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.name %></td>
        <td><%= event.description %></td>
        <td><%= event.start_time %></td>
        <td><%= event.end_time %></td>
        <td><%= event.ticket_link %></td>
        <td><%= event.expired %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %> 
<%
=end%>
<section class="better-space"></section>
<%= render 'shared/events_advert'%>
<section class="better-space"></section>
  <h2>Our categories</h2>
      <div data-slick='{"slidesToShow": 3, "slidesToScroll": 3}' class="scroller responsive data">
          <% @categories.each do |category| %>
                  <!-- Card example 06 -->
                  <div class="card card__small card__dark card__dark--magenta">
                      <div class="media" style="background-image: url(https://earlybirds.co.za<%= Rails.application.routes.url_helpers.rails_representation_url(category&.image.variant(resize: "500x500").processed, only_path: true) %>); background-repeat: no-repeat; background-size: cover;"></div>

                      <div class="primary-title">
                          <div class="primary-text"><%= link_to category.name, category_path(category), :class => "event-link" %></div>
                      </div>
                      <div class="actions border-top">
                          <div class="action-buttons">
                              <%= button_to "Learn more", category_path(category), :method => :get, :class => "button", :type => "button" %>
                          </div>
                      </div>
                  </div>
          <% end %>
  </div>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<%
=begin%>
 <p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @category.description %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %> 
<%
=end%>
<%
=begin%>
 <%= link_to 'Edit', edit_category_path(@category) %> | 
<%
=end%>
<%= link_to 'Back', categories_path %> 
<section id="sunfish">
  <div class="banner">
    <h2 class="mb-3 intro"><%= @category.name %></h2>
    <div>
      <figure>
        <%= image_tag @category.hero, :alt=>"earlybirds.co.za category banner", :class=>"event-show-banner" %>

        <figcaption class="top">
            <div class="overlay">
              <p id="text"><%= truncate(@category.description, length: 600) %></p>
            </div>
        <%
=begin%>
 <div class="overlay">
<%
=end%>
        </figcaption>

        <figcaption class="button"><%= button_to "Explore all events categories", categories_path, :class => "btn btn-bnb", :method => :get %></figcaption>
        <figcaption class="sign">
          <div class="_exn6n2"><svg viewBox="0 0 470 239" fill="#616668" height="50px" aria-label="" width="98.32635983263597px"></svg></div>
        </figcaption>
      </figure>
    </div>
  </div>
</section>


<section class="better-space"></section>
<%= render 'shared/daily_cards', header: "Trips for #{@category.name} event category", trips: trips_for_category(@category.id) %>
<section class="better-space"></section>
<%= render 'shared/daily_cards', header: "Trips for other events categories", trips: trips_for_other_events(@category.id) %> 